# Generated by Django 5.1.4 on 2024-12-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_register',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
