# Generated by Django 5.1.4 on 2025-01-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_register_date_register_alter_register_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='code',
        ),
        migrations.AddField(
            model_name='register',
            name='random_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
