# Generated by Django 5.1.4 on 2025-01-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_register_code_register_random_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='random_code',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_password',
        ),
        migrations.AlterField(
            model_name='register',
            name='date_register',
            field=models.DateField(null=True),
        ),
    ]
