# Generated by Django 5.1.4 on 2025-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_register_random_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='random_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
