# Generated by Django 5.1.4 on 2025-01-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_register_random_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='random_code',
        ),
        migrations.AddField(
            model_name='register',
            name='code',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
